version: "3.0"
services:
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - ST_network
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "ELASTIC_PASSWORD=${ELK_PASSWORD}"
#      - "xpack.security.enabled=true"

  logstash:
    image: logstash:7.8.0
    container_name: logstash
    hostname: logstash
    ports:
      - '5044:5044'
      - '8089:8089'
    networks:
      - ST_network
    volumes:
      - ./configs/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:7.8.0
    container_name: kibana
    hostname: kibana
    ports:
      - '5601:5601'
    networks:
      - ST_network
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
#    environment:
#      - "ELASTICSEARCH_USERNAME=elastic"
#      - "ELASTICSEARCH_PASSWORD=${ELK_PASSWORD}"

networks:
  ST_network:
    external: true
