version: "3.0"
services:
  redis:
    image: bitnami/redis:latest
    container_name: redis
    ports:
      - '7001:6379'
    networks:
      - ST_network
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=admin

networks:
  ST_network:
    external: true
