version: "3.0"
services:
  postgres:
    image: postgres:12
    container_name: postgres
    hostname: postgres
    restart: 'no'
    networks:
      - ST_network
    ports:
      - '5432:5432'
    volumes:
      - ./sql/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./sql/after_roll_up.sh:/usr/share/after_roll_up.sh
    environment:
      POSTGRES_PASSWORD: admin
      TZ: Europe/Moscow
    command: ["postgres", "-c", "log_statement=all"]

networks:
  ST_network:
    external: true