{
 "title": "coverage_PilotTeam",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Покрытие автотестами",
   "type": "stat",
   "gridPos": { "h": 19, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (automated_tests_run{label=\"PilotTeam\"} / total_test_cases{label=\"PilotTeam\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Кол-во Автотестов ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "automated_tests_run{label=\"PilotTeam\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Последний прогон",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_run", "legendFormat": "{{label}}" }
   ]
  },
  {
   "title": "Кол-во Test Cases",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "total_test_cases{label=\"PilotTeam\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flaky rate прогона",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(sum(rerun_tests) / sum(last_run))",
     "legendFormat": "{{label}}"
    }
   ]
  }
 ]
}