version: "3.0"
services:
  grpc_stub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_stub
    restart: 'no'
    ports:
      - '50051:50051'
      - '8022:8022'
    networks:
      - ST_network
    volumes:
      - ./example/:/app/
    environment:
      TZ: Europe/Moscow
      REST_PORT: 8022
      GRPC_PORT: 50051

networks:
  ST_network:
    external: true